### ISSUE TITLE
Could we use your code?

### ISSUE THREAD

**Issue by francesco-vannini** [jritter/brightpi#2]
Hi, just found this and wondered if we could use it on our main repo https://github.com/PiSupply/Bright-Pi

**Comment by jritter** [comment]
Hi @francesco-vannini, of course, take what you need, as long as you keep it open and accessible for everybody. Thanks for asking!

Regards, Jürg

**Comment by francesco-vannini** [comment]
Thanks Jürg it is very much appreciated
